apiVersion: v1
kind: Service
metadata:
  name: srvquizz
  labels:
    app: srvquizz
spec:
  selector:
    app: srvquizz
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: "35.195.67.45"
