apiVersion: v1
kind: Service
metadata:
  name: srvquizz
  labels:
    app: srvquizz
spec:
  selector:
    app: srvquizz
  ports:
  - port: 80
    targetPort: 6000
  type: LoadBalancer
  #loadBalancerIP: "<<to_be_provisioned>>"
